extends: default

rules:
  comments:
    require-starting-space: true
    min-spaces-from-content: 2
    ignore-shebangs: true
  document-start: disable
  key-duplicates: disable
  # key-ordering: enable
  line-length: disable
  trailing-spaces: disable
