extends: default

rules:
  comments:
    ignore-shebangs: true
    min-spaces-from-content: 2
    require-starting-space: true
  document-start: disable
  key-duplicates: disable
  key-ordering: disable
  line-length: disable
  trailing-spaces: disable
