name: CI

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - master
      - test_github_workflow
  pull_request:

permissions:
  contents: read

jobs:
  setup:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout`
      - name: Checkout Repo
        uses: actions/checkout@v3

      # https://github.com/marketplace/actions/setup-go-environment
      - name: Set up Go 1.x >= 1.18
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true

      # https://github.com/marketplace/actions/run-golangci-lint#how-to-use
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

      # https://github.com/marketplace/actions/goreleaser-action
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # KEY_GITHUB_GORELEASER_TO_HOMEBREW_TAP: ${{ secrets.KEY_GITHUB_GORELEASER_TO_HOMEBREW_TAP }}
